import { OrganizationRole } from '@stokku/database';

export const SYSTEM_ROLE_PERMISSIONS: Record<OrganizationRole, readonly string[]> = {
  OWNER: ['*'],
  ADMIN: ['*'],
  INVENTORY_MANAGER: [
    'product.read',
    'product.create',
    'product.update',
    'product.archive',
    'inventory.read',
    'inventory.adjust.request',
    'inventory.adjust.approve',
    'inventory.transfer.create',
    'inventory.transfer.dispatch',
    'inventory.transfer.receive',
    'inventory.reconcile',
    'po.read',
    'po.create',
    'po.submit',
    'po.approve',
    'po.send',
    'po.cancel',
    'receipt.create',
    'receipt.post',
    'receipt.reverse',
    'so.read',
    'so.create',
    'so.confirm',
    'so.cancel',
    'pick.execute',
    'pack.execute',
    'shipment.post',
    'cycle_count.create',
    'cycle_count.execute',
    'cycle_count.approve',
  ],
  WAREHOUSE_STAFF: [
    'product.read',
    'inventory.read',
    'inventory.adjust.request',
    'inventory.transfer.create',
    'inventory.transfer.dispatch',
    'inventory.transfer.receive',
    'po.read',
    'receipt.create',
    'receipt.post',
    'so.read',
    'pick.execute',
    'pack.execute',
  ],
  CASHIER: ['product.read', 'inventory.read', 'so.read', 'so.create'],
  VIEWER: ['product.read', 'inventory.read', 'po.read', 'so.read'],
};
